import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Nav from "@/app/components/nav";
import Footer from "@/app/components/footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme='dracula'>
        <body className={inter.className}>
        <Nav/>
        <main className='body-content'>
            <div className="text-sm my-3 breadcrumbs">
                <ul>
                    <li><a>Home</a></li>
                    <li><a>Documents</a></li>
                    <li>Add Document</li>
                </ul>
            </div>
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    );
}
